import { readFileSync } from "node:fs";
import { chmod, readFile, writeFile } from "node:fs/promises";
import { resolve } from "node:path";

const START = "# >>> Conclave CLI configuration >>>";
const END = "# <<< Conclave CLI configuration <<<";
const KEY_PATTERN = /^CONCLAVE_[A-Z0-9_]+$/;

function isMissingFile(error: unknown): boolean {
  return typeof error === "object" && error !== null && "code" in error && error.code === "ENOENT";
}

export interface EnvironmentFileLoadResult {
  readonly path: string;
  readonly loadedKeys: readonly string[];
}

export interface EnvironmentFileWriteResult {
  readonly path: string;
  readonly updated: boolean;
}

function decodeValue(value: string): string {
  const trimmed = value.trim();
  if (trimmed.startsWith('"') && trimmed.endsWith('"')) {
    try {
      const decoded: unknown = JSON.parse(trimmed);
      if (typeof decoded === "string") return decoded;
    } catch {
      return trimmed.slice(1, -1);
    }
  }
  if (trimmed.startsWith("'") && trimmed.endsWith("'")) return trimmed.slice(1, -1);
  const comment = trimmed.search(/\s#/);
  return (comment === -1 ? trimmed : trimmed.slice(0, comment)).trim();
}

function entries(content: string): ReadonlyMap<string, string> {
  const parsed = new Map<string, string>();
  for (const line of content.split(/\r?\n/u)) {
    const match = line.match(/^\s*(?:export\s+)?([A-Za-z_][A-Za-z0-9_]*)\s*=\s*(.*)$/u);
    if (match?.[1] === undefined || match[2] === undefined) continue;
    if (!KEY_PATTERN.test(match[1])) continue;
    parsed.set(match[1], decodeValue(match[2]));
  }
  return parsed;
}

/** Loads only CONCLAVE_* values, never overwriting values supplied by the process. */
export function loadConclaveEnvironment(
  environment: NodeJS.ProcessEnv = process.env,
  path = resolve(".env"),
): EnvironmentFileLoadResult {
  const resolvedPath = resolve(path);
  let content: string;
  try {
    content = readFileSync(resolvedPath, "utf8");
  } catch (error) {
    if (isMissingFile(error)) return { path: resolvedPath, loadedKeys: [] };
    throw error;
  }
  const loadedKeys: string[] = [];
  for (const [key, value] of entries(content)) {
    if (environment[key] !== undefined) continue;
    environment[key] = value;
    loadedKeys.push(key);
  }
  return { path: resolvedPath, loadedKeys };
}

function ensureSafeEntry(key: string, value: string): void {
  if (!KEY_PATTERN.test(key)) throw new Error(`Refusing to write a non-Conclave environment key: ${key}`);
  if (value.includes("\u0000") || value.includes("\n") || value.includes("\r")) {
    throw new Error(`Refusing to write a multiline value for ${key}`);
  }
}

function configurationBlock(values: Readonly<Record<string, string>>): string {
  const lines = Object.entries(values)
    .sort(([left], [right]) => left.localeCompare(right))
    .map(([key, value]) => {
      ensureSafeEntry(key, value);
      return `${key}=${JSON.stringify(value)}`;
    });
  return [START, "# Generated by `conclave init`. This file is ignored by Git.", ...lines, END].join("\n");
}

/** Replaces only the managed block so unrelated local variables and comments survive setup reruns. */
export async function writeConclaveEnvironment(
  path: string,
  values: Readonly<Record<string, string>>,
): Promise<EnvironmentFileWriteResult> {
  const resolvedPath = resolve(path);
  let existing: string;
  try {
    existing = await readFile(resolvedPath, "utf8");
  } catch (error) {
    if (!isMissingFile(error)) throw error;
    existing = "";
  }
  const start = existing.indexOf(START);
  const end = existing.indexOf(END);
  const duplicateStart = start === -1 ? -1 : existing.indexOf(START, start + START.length);
  const duplicateEnd = end === -1 ? -1 : existing.indexOf(END, end + END.length);
  if (
    (start === -1) !== (end === -1) ||
    (start !== -1 && end < start) ||
    duplicateStart !== -1 ||
    duplicateEnd !== -1
  ) {
    throw new Error(`Refusing to modify malformed Conclave configuration markers in ${resolvedPath}`);
  }
  const block = configurationBlock(values);
  const next = start === -1
    ? `${existing}${existing === "" || existing.endsWith("\n") ? "" : "\n"}${block}\n`
    : `${existing.slice(0, start)}${block}${existing.slice(end + END.length)}`;
  if (next !== existing) await writeFile(resolvedPath, next, { encoding: "utf8", mode: 0o600 });
  await chmod(resolvedPath, 0o600);
  return { path: resolvedPath, updated: next !== existing };
}
